version: '3'
services:
  subservice1:
    image: swizkon/sayhello
    ports:
      - "5061:80"
    environment:
      - SayHello:ServiceName=The first sub service
      
  subservice2:
    image: swizkon/sayhello
    ports:
      - "5062:80"
    environment:
      - SayHello:ServiceName=The second sub service
      
  pubweb:
    image: swizkon/sayhello
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5601:80"
    environment:
      - SayHello:ServiceName=TheName
      - SayHello:Siblings=http://subservice1 http://subservice2

  mailserver:
    image: mailhog/mailhog
    ports: 
     - "8025:8025"
     - "1025:1025"