version: '3'
services:
  subservice1:
    image: swizkon/sayhello
    ports:
      - "5061:80"
    environment:
      - SayHello:ServiceName=The first sub service
      
  subservice2:
    image: swizkon/sayhello
    ports:
      - "5062:80"
    environment:
      - SayHello:ServiceName=The second sub service
      
  pubweb:
    image: swizkon/sayhello
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5601:80"
    environment:
      - SayHello:ServiceName=TheName
      - SayHello:Siblings=http://subservice1 http://subservice2
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    depends_on: 
      - redis
      - azurite
      - mailserver
    links: 
      - azurite

  mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
  #   ports: 
  #     - "1433:1433"
  #   environment: 
  #     - "ACCEPT_EULA=Y"
  #     - "SA_PASSWORD=MyS3curep@ssW0rd"

  redis:
    image: redis
    ports:
      - "6379:6379"

  # docker run -d -t -p 10000:10000 -p 10001:10001 -p 10002:10002 -v /path/to/folder:/opt/azurite/folder arafato/azurite
  azurite:
    container_name: azurite
    image: arafato/azurite
    restart: always
    volumes: 
      - "~/Documents/AzuriteData:/data"
    ports: 
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
